-- SCRIPT DE CONFIGURAÇÃO DO BANCO DE DADOS EPIVIU (VERSÃO SEGURA)
-- Execute este script no SQL Editor do seu projeto Supabase

-- 1. Criar tabela de Equipe (Staff)
CREATE TABLE IF NOT EXISTS public.staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL DEFAULT auth.uid(), -- Segurança: Vincula ao usuário logado
    name TEXT NOT NULL,
    shift TEXT NOT NULL CHECK (shift IN ('morning', 'afternoon', 'oncall')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(name, user_id) -- Impede nomes duplicados para o mesmo usuário
);

-- 2. Criar tabela de Setores (Sectors)
CREATE TABLE IF NOT EXISTS public.sectors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL DEFAULT auth.uid(),
    name TEXT NOT NULL,
    staff_id BIGINT REFERENCES public.staff(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Criar tabela de Visitas Não Realizadas (Missed Visits)
CREATE TABLE IF NOT EXISTS public.missed_visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL DEFAULT auth.uid(),
    sector_id BIGINT REFERENCES public.sectors(id) ON DELETE CASCADE,
    visit_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(sector_id, visit_date)
);

-- 4. Habilitar Row Level Security (RLS)
ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sectors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.missed_visits ENABLE ROW LEVEL SECURITY;

-- 5. Políticas de Segurança (Garante isolamento entre usuários)
DROP POLICY IF EXISTS "Manage own staff" ON public.staff;
DROP POLICY IF EXISTS "Manage own sectors" ON public.sectors;
DROP POLICY IF EXISTS "Manage own missed visits" ON public.missed_visits;

CREATE POLICY "Manage own staff" ON public.staff FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Manage own sectors" ON public.sectors FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Manage own missed visits" ON public.missed_visits FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
