-- SCRIPT DE CONFIGURAÇÃO DO BANCO DE DADOS EPIVIU (VERSÃO SIMPLES)
-- Execute este script no SQL Editor do seu projeto Supabase

-- 1. Criar tabela de Equipe (Staff)
CREATE TABLE IF NOT EXISTS public.staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    shift TEXT NOT NULL CHECK (shift IN ('morning', 'afternoon', 'oncall')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Criar tabela de Setores (Sectors)
CREATE TABLE IF NOT EXISTS public.sectors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    staff_id BIGINT REFERENCES public.staff(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Criar tabela de Visitas Não Realizadas (Missed Visits)
CREATE TABLE IF NOT EXISTS public.missed_visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sector_id BIGINT REFERENCES public.sectors(id) ON DELETE CASCADE,
    visit_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(sector_id, visit_date)
);

-- 4. Desabilitar Row Level Security (RLS) para simplificar
ALTER TABLE public.staff DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sectors DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.missed_visits DISABLE ROW LEVEL SECURITY;

-- 5. Permitir acesso total para anon e authenticated (caso RLS esteja ativado por padrão)
DROP POLICY IF EXISTS "Public access" ON public.staff;
DROP POLICY IF EXISTS "Public access" ON public.sectors;
DROP POLICY IF EXISTS "Public access" ON public.missed_visits;

CREATE POLICY "Public access" ON public.staff FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.sectors FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.missed_visits FOR ALL USING (true) WITH CHECK (true);
