-- SCRIPT DE CONFIGURAÇÃO DO BANCO DE DADOS EPIVIU
-- Execute este script no SQL Editor do seu projeto Supabase

-- 1. Criar tabela de Equipe (Staff)
CREATE TABLE IF NOT EXISTS public.staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    shift TEXT NOT NULL CHECK (shift IN ('morning', 'afternoon', 'oncall')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Criar tabela de Setores (Sectors)
CREATE TABLE IF NOT EXISTS public.sectors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    staff_id BIGINT REFERENCES public.staff(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Criar tabela de Visitas Não Realizadas (Missed Visits)
CREATE TABLE IF NOT EXISTS public.missed_visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sector_id BIGINT REFERENCES public.sectors(id) ON DELETE CASCADE,
    visit_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(sector_id, visit_date)
);

-- 4. Habilitar Row Level Security (RLS)
ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sectors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.missed_visits ENABLE ROW LEVEL SECURITY;

-- 5. Criar Políticas de Acesso (RLS Policies)
-- Permitir que qualquer usuário autenticado leia e modifique os dados
-- (Ajuste conforme a necessidade de privacidade do hospital)

-- Políticas para STAFF
DO $$ BEGIN
    CREATE POLICY "Permitir leitura para usuários autenticados" ON public.staff FOR SELECT TO authenticated USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE POLICY "Permitir inserção para usuários autenticados" ON public.staff FOR INSERT TO authenticated WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE POLICY "Permitir atualização para usuários autenticados" ON public.staff FOR UPDATE TO authenticated USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE POLICY "Permitir exclusão para usuários autenticados" ON public.staff FOR DELETE TO authenticated USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Políticas para SECTORS
DO $$ BEGIN
    CREATE POLICY "Permitir leitura para usuários autenticados" ON public.sectors FOR SELECT TO authenticated USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE POLICY "Permitir inserção para usuários autenticados" ON public.sectors FOR INSERT TO authenticated WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE POLICY "Permitir atualização para usuários autenticados" ON public.sectors FOR UPDATE TO authenticated USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE POLICY "Permitir exclusão para usuários autenticados" ON public.sectors FOR DELETE TO authenticated USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Políticas para MISSED_VISITS
DO $$ BEGIN
    CREATE POLICY "Permitir leitura para usuários autenticados" ON public.missed_visits FOR SELECT TO authenticated USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE POLICY "Permitir inserção para usuários autenticados" ON public.missed_visits FOR INSERT TO authenticated WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE POLICY "Permitir atualização para usuários autenticados" ON public.missed_visits FOR UPDATE TO authenticated USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE POLICY "Permitir exclusão para usuários autenticados" ON public.missed_visits FOR DELETE TO authenticated USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
